#!/usr/bin/env python3
"""
train_yolo.py — Train YOLOv11 for Electronic Component Detection

Trains a YOLOv11 model on the synthetic dataset generated by
generate_yolo_dataset.py.

Usage:
    python train_yolo.py \
        --dataset yolo_dataset/dataset.yaml \
        --epochs 100 \
        --batch 16 \
        --model yolo11n.pt
"""

import argparse
import os


def parse_arguments():
    parser = argparse.ArgumentParser(description="Train YOLOv11 for Component Detection")
    parser.add_argument("--dataset", type=str, default="yolo_dataset/dataset.yaml",
                        help="Path to dataset.yaml")
    parser.add_argument("--model", type=str, default="yolo11n.pt",
                        help="Base YOLO model (yolo11n.pt, yolo11s.pt, yolo11m.pt)")
    parser.add_argument("--epochs", type=int, default=100,
                        help="Number of training epochs")
    parser.add_argument("--batch", type=int, default=16,
                        help="Batch size")
    parser.add_argument("--imgsz", type=int, default=640,
                        help="Input image size")
    parser.add_argument("--device", type=str, default="0",
                        help="CUDA device(s), e.g. '0' or '0,1'")
    parser.add_argument("--project", type=str, default="runs/detect",
                        help="Project directory for saving results")
    parser.add_argument("--name", type=str, default="component_detector",
                        help="Experiment name")
    parser.add_argument("--resume", action="store_true",
                        help="Resume training from last checkpoint")
    return parser.parse_args()


def main():
    args = parse_arguments()

    # Verify dataset exists
    if not os.path.exists(args.dataset):
        print(f"Error: Dataset file '{args.dataset}' not found.")
        print("Run generate_yolo_dataset.py first to create the training data.")
        return

    try:
        from ultralytics import YOLO
    except ImportError:
        print("Error: ultralytics not installed. Run: pip install ultralytics")
        return

    print("=" * 60)
    print("  YOLO Component Detector Training")
    print("=" * 60)
    print(f"  Dataset:  {args.dataset}")
    print(f"  Model:    {args.model}")
    print(f"  Epochs:   {args.epochs}")
    print(f"  Batch:    {args.batch}")
    print(f"  ImgSize:  {args.imgsz}")
    print(f"  Device:   {args.device}")
    print(f"  Project:  {args.project}")
    print(f"  Name:     {args.name}")
    print("=" * 60)

    # Load base model
    print(f"\nLoading base model: {args.model}")
    model = YOLO(args.model)

    # Train
    print("\nStarting training...")
    results = model.train(
        data=args.dataset,
        epochs=args.epochs,
        batch=args.batch,
        imgsz=args.imgsz,
        device=args.device,
        project=args.project,
        name=args.name,
        resume=args.resume,
        # Augmentation settings optimized for schematics
        hsv_h=0.0,       # No hue augmentation (schematics are black/white)
        hsv_s=0.0,       # No saturation augmentation
        hsv_v=0.2,       # Slight brightness variation
        degrees=0.0,     # No rotation (components have fixed orientations)
        translate=0.1,   # Slight translation
        scale=0.3,       # Scale variation
        flipud=0.0,      # No vertical flip
        fliplr=0.0,      # No horizontal flip (schematics are directional)
        mosaic=0.5,      # Some mosaic augmentation
        mixup=0.0,       # No mixup
        patience=20,     # Early stopping patience
        save=True,
        save_period=10,  # Save checkpoint every 10 epochs
        verbose=True,
    )

    # Print results
    print("\n" + "=" * 60)
    print("  Training Complete!")
    print("=" * 60)

    # Best weights path
    best_weights = os.path.join(args.project, args.name, "weights", "best.pt")
    if os.path.exists(best_weights):
        print(f"  Best weights saved to: {best_weights}")
    else:
        # Try to find it
        for root, dirs, files in os.walk(os.path.join(args.project, args.name)):
            for f in files:
                if f == "best.pt":
                    best_weights = os.path.join(root, f)
                    print(f"  Best weights saved to: {best_weights}")
                    break

    print(f"\n  To use the trained model with the SINA pipeline:")
    print(f"  python sina_pipeline.py --image_dir <images> --yolo_weights {best_weights} --output_dir sina_graphs")


if __name__ == "__main__":
    main()
